In [3]:
import pandas as pd
df = pd.read_csv("data_241_27022026.csv")

In [4]:
df.head()

              hour_ist                       epc  shutheight  hourly_count
0  2026-02-26 09:00:00  e200471690406821a3010110        0.00             2
1  2026-02-26 09:00:00  e200471690406821a3010110      320.07           287
2  2026-02-26 10:00:00  e200471690406821a3010110        0.00             1
3  2026-02-26 10:00:00  e200471690406821a3010110      320.07           348
4  2026-02-26 11:00:00  e200471690406821a3010110        0.00             1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   hour_ist      33 non-null     object
 1   epc           33 non-null     object
 2   shutheight    33 non-null     float64
 3   hourly_count  33 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.2+ KB

In [6]:
import numpy as np

df_copy = df.copy()

df_copy['shutheight'] = (
    df_copy['shutheight']
        .replace(0, np.nan)
        .bfill()
)

df_copy.head()

              hour_ist                       epc  shutheight  hourly_count
0  2026-02-26 09:00:00  e200471690406821a3010110      320.07             2
1  2026-02-26 09:00:00  e200471690406821a3010110      320.07           287
2  2026-02-26 10:00:00  e200471690406821a3010110      320.07             1
3  2026-02-26 10:00:00  e200471690406821a3010110      320.07           348
4  2026-02-26 11:00:00  e200471690406821a3010110      320.07             1

In [7]:
df_final = (
    df_copy
        .groupby(['hour_ist', 'epc', 'shutheight'], as_index=False)
        .agg({'hourly_count': 'sum'})
)

In [8]:
df_final.head()

              hour_ist                       epc  shutheight  hourly_count
0  2026-02-26 09:00:00  e200471690406821a3010110      320.07           289
1  2026-02-26 10:00:00  e200471690406821a3010110      320.07           349
2  2026-02-26 11:00:00  e200471690406821a3010110      320.07           195
3  2026-02-26 12:00:00  e200471690406821a3010110      320.07            95
4  2026-02-26 13:00:00  e200471690406821a3010110      320.07           225

In [9]:
df_final = df_final.sort_values('hour_ist')

In [10]:
df_final

               hour_ist                       epc  shutheight  hourly_count
0   2026-02-26 09:00:00  e200471690406821a3010110      320.07           289
1   2026-02-26 10:00:00  e200471690406821a3010110      320.07           349
2   2026-02-26 11:00:00  e200471690406821a3010110      320.07           195
3   2026-02-26 12:00:00  e200471690406821a3010110      320.07            95
4   2026-02-26 13:00:00  e200471690406821a3010110      320.07           225
5   2026-02-26 14:00:00  e200471690406821a3010110      320.07           196
6   2026-02-26 15:00:00  e200471690406821a3010110      320.07           218
7   2026-02-26 16:00:00  e00000000000000000000002      320.07             1
8   2026-02-26 16:00:00  e200471690406821a3010110      320.07           140
11  2026-02-26 17:00:00  e200471670a06821a107010d      322.96             2
12  2026-02-26 17:00:00  e200471670a06821a107010d      342.11             1
9   2026-02-26 17:00:00  e200471670a06821a107010d      322.03           143
10  2026-02-26 17:00:00  e200471670a06821a107010d      322.17             1
13  2026-02-26 18:00:00  e00000000000000000000002      322.03             1
14  2026-02-26 18:00:00  e200471670a06821a107010d      322.03            60
15  2026-02-26 18:00:00  e200471690406821a3010110      319.87             2
16  2026-02-26 18:00:00  e200471690406821a3010110      320.01             2
17  2026-02-26 18:00:00  e200471690406821a3010110      320.18             2
18  2026-02-26 18:00:00  e200471690406821a3010110      320.73             1
19  2026-02-26 18:00:00  e200471690406821a3010110      321.77             1
20  2026-02-26 18:00:00  e200471690406821a3010110      323.19             1
21  2026-02-26 18:00:00  e200471690406821a3010110      324.58             1
22  2026-02-26 18:00:00  e200471690406821a3010110      337.43             2
23  2026-02-26 20:00:00  e200471690406821a3010110      319.87           125
24  2026-02-26 21:00:00  e200471690406821a3010110      319.87           247

In [11]:
epc_value = "e200471690406821a3010110"

df_filtered = df_final[df_final['epc'] == epc_value]

df_filtered

               hour_ist                       epc  shutheight  hourly_count
0   2026-02-26 09:00:00  e200471690406821a3010110      320.07           289
1   2026-02-26 10:00:00  e200471690406821a3010110      320.07           349
2   2026-02-26 11:00:00  e200471690406821a3010110      320.07           195
3   2026-02-26 12:00:00  e200471690406821a3010110      320.07            95
4   2026-02-26 13:00:00  e200471690406821a3010110      320.07           225
5   2026-02-26 14:00:00  e200471690406821a3010110      320.07           196
6   2026-02-26 15:00:00  e200471690406821a3010110      320.07           218
8   2026-02-26 16:00:00  e200471690406821a3010110      320.07           140
15  2026-02-26 18:00:00  e200471690406821a3010110      319.87             2
16  2026-02-26 18:00:00  e200471690406821a3010110      320.01             2
17  2026-02-26 18:00:00  e200471690406821a3010110      320.18             2
18  2026-02-26 18:00:00  e200471690406821a3010110      320.73             1
19  2026-02-26 18:00:00  e200471690406821a3010110      321.77             1
20  2026-02-26 18:00:00  e200471690406821a3010110      323.19             1
21  2026-02-26 18:00:00  e200471690406821a3010110      324.58             1
22  2026-02-26 18:00:00  e200471690406821a3010110      337.43             2
23  2026-02-26 20:00:00  e200471690406821a3010110      319.87           125
24  2026-02-26 21:00:00  e200471690406821a3010110      319.87           247

In [12]:
df_final[df_final['epc'] == epc_value]['hourly_count'].sum()

np.int64(2091)