In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("data_245_26022026.csv")


df_copy = df.copy()

df_copy['shutheight'] = (
    df_copy['shutheight']
        .replace(0, np.nan)
        .bfill()
)

df_final = (
    df_copy
        .groupby(['hour_ist', 'epc', 'shutheight'], as_index=False)
        .agg({'hourly_count': 'sum'})
)
df_final = df_final.sort_values('hour_ist')
df_final

               hour_ist                       epc  shutheight  hourly_count
0   2026-02-26 09:00:00  e00000000000000000000002      321.24             1
18  2026-02-26 09:00:00  e00000000000000000000002      328.53             1
16  2026-02-26 09:00:00  e00000000000000000000002      325.61             1
15  2026-02-26 09:00:00  e00000000000000000000002      324.95             1
14  2026-02-26 09:00:00  e00000000000000000000002      324.42             2
13  2026-02-26 09:00:00  e00000000000000000000002      323.66             1
12  2026-02-26 09:00:00  e00000000000000000000002      323.26             1
11  2026-02-26 09:00:00  e00000000000000000000002      323.03             2
10  2026-02-26 09:00:00  e00000000000000000000002      322.79             1
17  2026-02-26 09:00:00  e00000000000000000000002      326.37             2
8   2026-02-26 09:00:00  e00000000000000000000002      322.27             3
7   2026-02-26 09:00:00  e00000000000000000000002      322.10             4
6   2026-02-26 09:00:00  e00000000000000000000002      322.01             7
5   2026-02-26 09:00:00  e00000000000000000000002      321.95             4
4   2026-02-26 09:00:00  e00000000000000000000002      321.90             4
3   2026-02-26 09:00:00  e00000000000000000000002      321.84             7
2   2026-02-26 09:00:00  e00000000000000000000002      321.56             1
1   2026-02-26 09:00:00  e00000000000000000000002      321.41             1
9   2026-02-26 09:00:00  e00000000000000000000002      322.38             1
23  2026-02-26 10:00:00  e00000000000000000000002      321.08             2
21  2026-02-26 10:00:00  e00000000000000000000002      320.84             6
22  2026-02-26 10:00:00  e00000000000000000000002      320.95             5
19  2026-02-26 10:00:00  e00000000000000000000002      320.60            49
20  2026-02-26 10:00:00  e00000000000000000000002      320.77             3
24  2026-02-26 11:00:00  e00000000000000000000002      320.60           114
25  2026-02-26 12:00:00  e00000000000000000000002      320.60            68
26  2026-02-26 13:00:00  e00000000000000000000002      320.60           152
27  2026-02-26 14:00:00  e00000000000000000000002      320.60           180
28  2026-02-26 15:00:00  e00000000000000000000002      320.60           263
29  2026-02-26 16:00:00  e00000000000000000000002      320.60           129
30  2026-02-26 17:00:00  e00000000000000000000002      320.60           197
31  2026-02-26 18:00:00  e00000000000000000000002      320.60           140
32  2026-02-26 19:00:00  e00000000000000000000002      320.60           126
33  2026-02-26 21:00:00  e00000000000000000000002      320.60            96
34  2026-02-26 22:00:00  e00000000000000000000002      320.60            49

In [2]:
epc_value = "e00000000000000000000002"

df_filtered = df_final[df_final['epc'] == epc_value]

df_filtered

               hour_ist                       epc  shutheight  hourly_count
0   2026-02-26 09:00:00  e00000000000000000000002      321.24             1
18  2026-02-26 09:00:00  e00000000000000000000002      328.53             1
16  2026-02-26 09:00:00  e00000000000000000000002      325.61             1
15  2026-02-26 09:00:00  e00000000000000000000002      324.95             1
14  2026-02-26 09:00:00  e00000000000000000000002      324.42             2
13  2026-02-26 09:00:00  e00000000000000000000002      323.66             1
12  2026-02-26 09:00:00  e00000000000000000000002      323.26             1
11  2026-02-26 09:00:00  e00000000000000000000002      323.03             2
10  2026-02-26 09:00:00  e00000000000000000000002      322.79             1
17  2026-02-26 09:00:00  e00000000000000000000002      326.37             2
8   2026-02-26 09:00:00  e00000000000000000000002      322.27             3
7   2026-02-26 09:00:00  e00000000000000000000002      322.10             4
6   2026-02-26 09:00:00  e00000000000000000000002      322.01             7
5   2026-02-26 09:00:00  e00000000000000000000002      321.95             4
4   2026-02-26 09:00:00  e00000000000000000000002      321.90             4
3   2026-02-26 09:00:00  e00000000000000000000002      321.84             7
2   2026-02-26 09:00:00  e00000000000000000000002      321.56             1
1   2026-02-26 09:00:00  e00000000000000000000002      321.41             1
9   2026-02-26 09:00:00  e00000000000000000000002      322.38             1
23  2026-02-26 10:00:00  e00000000000000000000002      321.08             2
21  2026-02-26 10:00:00  e00000000000000000000002      320.84             6
22  2026-02-26 10:00:00  e00000000000000000000002      320.95             5
19  2026-02-26 10:00:00  e00000000000000000000002      320.60            49
20  2026-02-26 10:00:00  e00000000000000000000002      320.77             3
24  2026-02-26 11:00:00  e00000000000000000000002      320.60           114
25  2026-02-26 12:00:00  e00000000000000000000002      320.60            68
26  2026-02-26 13:00:00  e00000000000000000000002      320.60           152
27  2026-02-26 14:00:00  e00000000000000000000002      320.60           180
28  2026-02-26 15:00:00  e00000000000000000000002      320.60           263
29  2026-02-26 16:00:00  e00000000000000000000002      320.60           129
30  2026-02-26 17:00:00  e00000000000000000000002      320.60           197
31  2026-02-26 18:00:00  e00000000000000000000002      320.60           140
32  2026-02-26 19:00:00  e00000000000000000000002      320.60           126
33  2026-02-26 21:00:00  e00000000000000000000002      320.60            96
34  2026-02-26 22:00:00  e00000000000000000000002      320.60            49

In [3]:
df_final[df_final['epc'] == epc_value]['hourly_count'].sum()

np.int64(1624)

In [4]:
# epc_value = "e200471649e068219e9b0112"

# df_filtered = df_final[df_final['epc'] == epc_value]

# df_filtered

# df_final[df_final['epc'] == epc_value]['hourly_count'].sum()