In [1]:
import pandas as pd

In [7]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [8]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [9]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [10]:
pd.merge(employees,departments,on="DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [11]:
# Left Join
pd.merge(employees,departments,on="DeptID",how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [12]:
# Right Join
pd.merge(employees,departments,on="DeptID",how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
# Outer Join
pd.merge(employees,departments,on="DeptID",how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

## Concatenating DataFrames

In [14]:
df1 = pd.DataFrame({"Name":["Alice","Bob"]})
df2 = pd.DataFrame({"Name":["Charlie","David"]})

In [15]:
df1

    Name
0  Alice
1    Bob

In [16]:
df2

      Name
0  Charlie
1    David

In [17]:
# Vertical
pd.concat([df1,df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [18]:
# Horizontal
pd.concat([df1,df2],axis=1)

    Name     Name
0  Alice  Charlie
1    Bob    David